Config.TheoryTest = {
    {
        forLicense = 'bike_license', -- do not use one license in more than one test!
        maxErrorPoints = 9,          -- max. amount of error points to pass the test
        maxQuestions = 10,           -- max. amount of questions to ask
        questions = {
            [1] = {
                question = "What is the speed limit in urban areas?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "C" },
            },
            [2] = {
                question = "What is the speed limit outside urban areas?",
                answerA = "50 km/h",
                answerB = "70 km/h",
                answerC = "100 km/h",
                answerD = "120 km/h",
                errorPoints = 3,
                rightAnswers = { "C" },
            },
            [3] = {
                question = "Which statement is false?",
                answerA = "The driver must follow traffic rules.",
                answerB = "The motorcycle can only be powered by gasoline.",
                answerC = "The driver must have a driver's license.",
                answerD = "The driver doesn't need to wear a helmet.",
                errorPoints = 4,
                rightAnswers = { "D" },
            },
            [4] = {
                question = "What is aquaplaning?",
                answerA = "When the vehicle suddenly skids on a wet road.",
                answerB = "An Indonesian street race in the summer.",
                answerC = "An unplanned water damage in the engine compartment.",
                answerD = "A swimming pool.",
                errorPoints = 3,
                rightAnswers = { "A" },
            },
            [5] = {
                question = "You hear a siren. What questions should you ask yourself at this moment?",
                answerA = "Where is the emergency vehicle coming from?",
                answerB = "Is the vehicle allowed to use the siren?",
                answerC = "Is the blue light even approved?",
                answerD = "Could the emergency vehicle be hindered by me?",
                errorPoints = 1,
                rightAnswers = { "A", "D" },
            },
            [6] = {
                question = "When should the light be turned on?",
                answerA = "Only in darkness",
                answerB = "Only in rain",
                answerC = "Only in fog",
                answerD = "The light must always be on for motorcycles",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [7] = {
                question = "When can the horn's warning sound be used?",
                answerA = "Only to warn of dangers",
                answerB = "Only to greet other road users",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "Never",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [8] = {
                question = "When do motorcycles have to undergo a main inspection?",
                answerA = "Before each re-registration",
                answerB = "at one's discretion",
                answerC = "Every three years",
                answerD = "Every two years",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [9] = {
                question = "You are driving on a highway with light traffic density. How long can you use the left lane?",
                answerA = "As long as necessary to overtake other vehicles",
                answerB = "Constantly, as long as no other vehicle wants to overtake you",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "As long as you are driving behind a vehicle that is overtaking in the left lane",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [10] = {
                question = "What is the maximum speed limit in a built-up area?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "B" },
            },
        }
    },
    {
        forLicense = 'car_license',
        maxErrorPoints = 9,
        maxQuestions = 10, -- max. amount of questions to ask
        questions = {
            [1] = {
                question = "What is the speed limit in urban areas?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "C" },
            },
            [2] = {
                question = "What is the speed limit outside urban areas?",
                answerA = "50 km/h",
                answerB = "70 km/h",
                answerC = "100 km/h",
                answerD = "120 km/h",
                errorPoints = 3,
                rightAnswers = { "C" },
            },
            [3] = {
                question = "Which statement is false?",
                answerA = "The driver must follow traffic rules.",
                answerB = "The motorcycle can only be powered by gasoline.",
                answerC = "The driver must have a driver's license.",
                answerD = "The driver doesn't need to wear a helmet.",
                errorPoints = 4,
                rightAnswers = { "D" },
            },
            [4] = {
                question = "What is aquaplaning?",
                answerA = "When the vehicle suddenly skids on a wet road.",
                answerB = "An Indonesian street race in the summer.",
                answerC = "An unplanned water damage in the engine compartment.",
                answerD = "A swimming pool.",
                errorPoints = 3,
                rightAnswers = { "A" },
            },
            [5] = {
                question = "You hear a siren. What questions should you ask yourself at this moment?",
                answerA = "Where is the emergency vehicle coming from?",
                answerB = "Is the vehicle allowed to use the siren?",
                answerC = "Is the blue light even approved?",
                answerD = "Could the emergency vehicle be hindered by me?",
                errorPoints = 1,
                rightAnswers = { "A", "D" },
            },
            [6] = {
                question = "When should the light be turned on?",
                answerA = "Only in darkness",
                answerB = "Only in rain",
                answerC = "Only in fog",
                answerD = "The light must always be on for motorcycles",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [7] = {
                question = "When can the horn's warning sound be used?",
                answerA = "Only to warn of dangers",
                answerB = "Only to greet other road users",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "Never",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [8] = {
                question = "When do motorcycles have to undergo a main inspection?",
                answerA = "Before each re-registration",
                answerB = "at one's discretion",
                answerC = "Every three years",
                answerD = "Every two years",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [9] = {
                question = "You are driving on a highway with light traffic density. How long can you use the left lane?",
                answerA = "As long as necessary to overtake other vehicles",
                answerB = "Constantly, as long as no other vehicle wants to overtake you",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "As long as you are driving behind a vehicle that is overtaking in the left lane",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [10] = {
                question = "What is the maximum speed limit in a built-up area?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "B" },
            },
        }
    },
    {
        forLicense = 'truck_license', -- do not use one license in more than one test!
        maxErrorPoints = 7,           -- min. amount of right answers to pass the test
        maxQuestions = 10,            -- max. amount of questions to ask
        questions = {
            [1] = {
                question = "What is the speed limit in urban areas?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "C" },
            },
            [2] = {
                question = "What is the speed limit outside urban areas?",
                answerA = "50 km/h",
                answerB = "70 km/h",
                answerC = "100 km/h",
                answerD = "120 km/h",
                errorPoints = 3,
                rightAnswers = { "C" },
            },
            [3] = {
                question = "Which statement is false?",
                answerA = "The driver must follow traffic rules.",
                answerB = "The motorcycle can only be powered by gasoline.",
                answerC = "The driver must have a driver's license.",
                answerD = "The driver doesn't need to wear a helmet.",
                errorPoints = 4,
                rightAnswers = { "D" },
            },
            [4] = {
                question = "What is aquaplaning?",
                answerA = "When the vehicle suddenly skids on a wet road.",
                answerB = "An Indonesian street race in the summer.",
                answerC = "An unplanned water damage in the engine compartment.",
                answerD = "A swimming pool.",
                errorPoints = 3,
                rightAnswers = { "A" },
            },
            [5] = {
                question = "You hear a siren. What questions should you ask yourself at this moment?",
                answerA = "Where is the emergency vehicle coming from?",
                answerB = "Is the vehicle allowed to use the siren?",
                answerC = "Is the blue light even approved?",
                answerD = "Could the emergency vehicle be hindered by me?",
                errorPoints = 1,
                rightAnswers = { "A", "D" },
            },
            [6] = {
                question = "When should the light be turned on?",
                answerA = "Only in darkness",
                answerB = "Only in rain",
                answerC = "Only in fog",
                answerD = "The light must always be on for motorcycles",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [7] = {
                question = "When can the horn's warning sound be used?",
                answerA = "Only to warn of dangers",
                answerB = "Only to greet other road users",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "Never",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [8] = {
                question = "When do motorcycles have to undergo a main inspection?",
                answerA = "Before each re-registration",
                answerB = "at one's discretion",
                answerC = "Every three years",
                answerD = "Every two years",
                errorPoints = 1,
                rightAnswers = { "D" },
            },
            [9] = {
                question = "You are driving on a highway with light traffic density. How long can you use the left lane?",
                answerA = "As long as necessary to overtake other vehicles",
                answerB = "Constantly, as long as no other vehicle wants to overtake you",
                answerC = "Only to express anger or dissatisfaction",
                answerD = "As long as you are driving behind a vehicle that is overtaking in the left lane",
                errorPoints = 1,
                rightAnswers = { "A" },
            },
            [10] = {
                question = "What is the maximum speed limit in a built-up area?",
                answerA = "30 km/h",
                answerB = "50 km/h",
                answerC = "80 km/h",
                answerD = "100 km/h",
                errorPoints = 1,
                rightAnswers = { "B" },
            },
        },
        {
            forLicense = 'truck_license', -- do not use one license in more than one test!
            maxErrorPoints = 7,           -- min. amount of right answers to pass the test
            maxQuestions = 10,            -- max. amount of questions to ask
            questions = {
                [1] = {
                    question = "What is the speed limit in urban areas?",
                    answerA = "30 km/h",
                    answerB = "50 km/h",
                    answerC = "80 km/h",
                    answerD = "100 km/h",
                    errorPoints = 1,
                    rightAnswers = { "C" },
                },
                [2] = {
                    question = "What is the speed limit outside urban areas?",
                    answerA = "50 km/h",
                    answerB = "70 km/h",
                    answerC = "100 km/h",
                    answerD = "120 km/h",
                    errorPoints = 3,
                    rightAnswers = { "C" },
                },
                [3] = {
                    question = "Which statement is false?",
                    answerA = "The driver must follow traffic rules.",
                    answerB = "The motorcycle can only be powered by gasoline.",
                    answerC = "The driver must have a driver's license.",
                    answerD = "The driver doesn't need to wear a helmet.",
                    errorPoints = 4,
                    rightAnswers = { "D" },
                },
                [4] = {
                    question = "What is aquaplaning?",
                    answerA = "When the vehicle suddenly skids on a wet road.",
                    answerB = "An Indonesian street race in the summer.",
                    answerC = "An unplanned water damage in the engine compartment.",
                    answerD = "A swimming pool.",
                    errorPoints = 3,
                    rightAnswers = { "A" },
                },
                [5] = {
                    question = "You hear a siren. What questions should you ask yourself at this moment?",
                    answerA = "Where is the emergency vehicle coming from?",
                    answerB = "Is the vehicle allowed to use the siren?",
                    answerC = "Is the blue light even approved?",
                    answerD = "Could the emergency vehicle be hindered by me?",
                    errorPoints = 1,
                    rightAnswers = { "A", "D" },
                },
                [6] = {
                    question = "When should the light be turned on?",
                    answerA = "Only in darkness",
                    answerB = "Only in rain",
                    answerC = "Only in fog",
                    answerD = "The light must always be on for motorcycles",
                    errorPoints = 1,
                    rightAnswers = { "D" },
                },
                [7] = {
                    question = "When can the horn's warning sound be used?",
                    answerA = "Only to warn of dangers",
                    answerB = "Only to greet other road users",
                    answerC = "Only to express anger or dissatisfaction",
                    answerD = "Never",
                    errorPoints = 1,
                    rightAnswers = { "A" },
                },
                [8] = {
                    question = "When do motorcycles have to undergo a main inspection?",
                    answerA = "Before each re-registration",
                    answerB = "at one's discretion",
                    answerC = "Every three years",
                    answerD = "Every two years",
                    errorPoints = 1,
                    rightAnswers = { "D" },
                },
                [9] = {
                    question =
                    "You are driving on a highway with light traffic density. How long can you use the left lane?",
                    answerA = "As long as necessary to overtake other vehicles",
                    answerB = "Constantly, as long as no other vehicle wants to overtake you",
                    answerC = "Only to express anger or dissatisfaction",
                    answerD = "As long as you are driving behind a vehicle that is overtaking in the left lane",
                    errorPoints = 1,
                    rightAnswers = { "A" },
                },
                [10] = {
                    question = "What is the maximum speed limit in a built-up area?",
                    answerA = "30 km/h",
                    answerB = "50 km/h",
                    answerC = "80 km/h",
                    answerD = "100 km/h",
                    errorPoints = 1,
                    rightAnswers = { "B" },
                },
            },
        },
    }
}
